#!/usr/bin/python
import subprocess
myFile = open("/var/www/scripts/data/logfail.txt","r")
ReadFile = open("/var/www/scripts/data/logfaildone.txt",'r')
line1 = 0
line2 = 0
for line in myFile:
	if line.strip():
		line1 += 1
for linen in ReadFile:
	if linen.strip():
		line2 += 1		
if line1 != line2:
	subprocess.call('thesms')
	print("sms")

subprocess.call('cplog')
